name: CLI BUMP VERSION $(PACKAGE) $(TARGET_PACKAGE_VERSION) $(Date:yyyyMMdd)

resources:
- repo: self

trigger:
  branches:
    exclude:
    - '*'

jobs:
- job: BumpVersionPython310
  displayName: CLI Bump Version Python310
  timeoutInMinutes: 9999
  strategy:
    maxParallel: 8
    matrix:
      instance1:
        Instance_idx: 1
      instance2:
        Instance_idx: 2
      instance3:
        Instance_idx: 3
      instance4:
        Instance_idx: 4
      instance5:
        Instance_idx: 5
      instance6:
        Instance_idx: 6
      instance7:
        Instance_idx: 7
      instance8:
        Instance_idx: 8
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        displayName: "Use Python 3.10"
    - bash: |
        set -ev
        ls

        echo package: $(PACKAGE) $(TARGET_PACKAGE_VERSION)
        echo resource_type: $(RESOURCE_TYPE) $(TARGET_API_VERSION)

        if [[ not $(PACKAGE) or not $(TARGET_PACKAGE_VERSION)]]; then
          echo "'PACKAGE' and 'TARGET_PACKAGE_VERSION' are required"
          exit 1
        fi
        sed -i "s/'$(PACKAGE)==.*'/'$(PACKAGE)==$(TARGET_PACKAGE_VERSION)'/g" ./src/azure-cli/setup.py
        sed -i "s/$(PACKAGE)==.*/$(PACKAGE)==$(TARGET_PACKAGE_VERSION)/g" ./src/azure-cli/requirements.py3.windows.txt
        sed -i "s/$(PACKAGE)==.*/$(PACKAGE)==$(TARGET_PACKAGE_VERSION)/g" ./src/azure-cli/requirements.py3.Linux.txt
        sed -i "s/$(PACKAGE)==.*/$(PACKAGE)==$(TARGET_PACKAGE_VERSION)/g" ./src/azure-cli/requirements.py3.Darwin.txt

        if [[ -n $(RESOURCE_TYPE) ]]; then
          python scripts/bump_version/update_api_profile.py "$(RESOURCE_TYPE)" "$(TARGET_API_VERSION)"
        fi
      displayName: "update version"
    - template: ../../.azure-pipelines/templates/azdev_setup.yml
    - bash: |
        serial_modules="appservice botservice cloud network azure-cli-core azure-cli-telemetry"
        python scripts/ci/automation_full_test.py "8" "$(Instance_idx)" "latest" "$serial_modules"
      displayName: "azdev test"